### ISSUE TITLE
Allows customization of patterns

### ISSUE THREAD

**Issue by kitsuyui** [kitsuyui/happy-commit#8]
Lucky/unlucky numbers have diverse cultural and religious backgrounds. Also, some teams may want to celebrate numbers or hashes that have special meaning.

Allows optional patterns to be added in addition to the default pattern.

I have an idea like this:
```yaml
      - uses: kitsuyui/lucky-commit
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          use_default_pattern: false
          additional_patterns:
            commits:
              - ['/666/', 'Wow! The commit {commtit} contains 666']
            issues:
              - ['666', 'Wow! The issue {issue} is 666']
```
